name: Deploy to GitHub-Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy

    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'

        run: npm —Åi

        run: npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          single-commit: true
